# build
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# serve
FROM nginx:alpine

# borrar el html default de nginx
RUN rm -rf /usr/share/nginx/html/*

# copiar la app real (SSR deja todo en /browser)
COPY --from=build /app/dist/frontend/browser /usr/share/nginx/html

# config SPA
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
